- name: Install pkgs
  hosts: all
  become: yes
  tasks:

    - name: Install packages using apt
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - vim
        - curl
        - unzip
        - htop
        - tmux
        
