---
- name: Install and Configure Node Exporter
  hosts: all
  become: yes
  vars:
    node_exporter_version: "1.10.2"
    node_exporter_user: "node_exporter"
    node_exporter_group: "node_exporter"
    node_exporter_port: 9100

  tasks:
    - name: Create node_exporter system group
      group:
        name: "{{ node_exporter_group }}"
        system: yes
        state: present

    - name: Create node_exporter system user
      user:
        name: "{{ node_exporter_user }}"
        system: yes
        shell: /sbin/nologin
        group: "{{ node_exporter_group }}"
        createhome: no

    - name: Download Node Exporter
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-386.tar.gz"
        dest: /tmp/node_exporter.tar.gz
        mode: '0644'

    - name: Extract Node Exporter
      unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /tmp
        remote_src: yes

    - name: Copy Node Exporter binary
      copy:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-386/node_exporter"
        dest: /usr/local/bin/node_exporter
        owner: "{{ node_exporter_user }}"
        group: "{{ node_exporter_group }}"
        mode: '0755'
        remote_src: yes

    - name: Create systemd service file
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          After=network.target

          [Service]
          Type=simple
          User={{ node_exporter_user }}
          Group={{ node_exporter_group }}
          ExecStart=/usr/local/bin/node_exporter --web.listen-address=:{{ node_exporter_port }}
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start Node Exporter service
      systemd:
        name: node_exporter
        enabled: yes
        state: started

    - name: Clean up temporary files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/node_exporter.tar.gz
        - "/tmp/node_exporter-{{ node_exporter_version }}.linux-386"

    - name: Wait for Node Exporter to be ready
      wait_for:
        port: "{{ node_exporter_port }}"
        delay: 2
        timeout: 30

    - name: Verify Node Exporter is responding
      uri:
        url: "http://localhost:{{ node_exporter_port }}/metrics"
        method: GET
        status_code: 200
      register: result
      retries: 3
      delay: 5
      until: result.status == 200
